### ISSUE TITLE
Warnings with latest versions of libraries

### ISSUE THREAD

**Issue by Engelberg** [hoplon/javelin#17]
With the following entries in my project file:

```
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-2311"]
                 [tailrecursion/javelin "3.6.0"]
                 [org.clojure/core.async "0.1.319.0-6b1aca-alpha"]
                 [prismatic/dommy "0.1.3"]]

  :plugins [[lein-cljsbuild "1.0.3"]]
```

I am receiving a bunch of warnings like the following:

```
WARNING: Symbol ILookup is not a protocol at line 7 file:/C:/Users/mark/.m2/repository/tailrecursion/cljs-priority-map/1.0.3/cljs-priority-map-1.0.3.jar!/tailrecursion/priority_map.cljs
```

It appears that the formula cells are not working properly, due to these warnings.

Any idea what is causing these warnings, or can you suggest a combination of relatively recent dependencies known to work with javelin?

**Comment by thedavidmeister** [comment]
this issue is super old and references thoroughly obsolete versions of cljs/javelin.

please feel free to reopen/comment if this is still a problem.
