### ISSUE TITLE
Importing from MS Excel

### ISSUE THREAD

**Issue by Quasaur** [hoplon/javelin#22]
Do you have any recommendations for importing data from MS Excel spreadsheets into a matrix of Javelin cells?

**Comment by thedavidmeister** [comment]
this is a very old issue now, but basically what you would want to do is (for the next person to find this issue):

1. find a way to get the spreadsheet data into native clojurescript as a CSV
2. convert the CSV into a useful data structure, like a list of hash maps for example
3. (optional) use something to query the data structure, e.g. https://github.com/alandipert/intension

i would recommend against trying to turn every spreadsheet cell into a javelin cells.

all cells (in both spreadsheets and javelin) are one of two types:

- read/write cells that store and propagate values with no additional logic
- read only cells that combine the values of other cells with a formula/expression into a single new value

you could probably map all the read/write cells from your spreadsheet into javelin cells, but unfortunately excel formulas and clojure code wouldn't line up well enough to support read only cells.

you're probably much better off importing the entire spreadsheet into a read/write cell then handle parsing/querying/manipulating that data in javelin read cells.
