### ISSUE TITLE
priority-map 0.0.7

### ISSUE THREAD

**Issue by laforge49** [hoplon/javelin#26]
Javelin uses priority-map version 0.0.2, which is really old.

Notify uses priority-map version 0.0.7, but restricting the requires to just priority-map-keyfn, which is not in version 0.0.2, seems to do the trick.

Even so, Javelin should probably be updated to use the newer version.

**Comment by micha** [comment]
Javelin no longer uses the priority map, so closing this issue :dancing_women:
